import 'dart:async';

import '../../models/territory.dart';
import 'territory_repository.dart';

/// In-memory territory repository — used when Firebase is unavailable.
/// Data is local only; changes do not persist across restarts.
class LocalTerritoryRepository implements TerritoryRepository {
  LocalTerritoryRepository() {
    _territories = _defaultTerritories();
  }

  late List<Territory> _territories;
  final _controller = StreamController<List<Territory>>.broadcast();

  void _emit() => _controller.add(List.unmodifiable(_territories));

  /// Immediately yields current state, then streams all future updates.
  @override
  Stream<List<Territory>> watchTerritories() async* {
    yield List.unmodifiable(_territories);
    yield* _controller.stream;
  }

  @override
  Future<void> claimTerritory({
    required String territoryId,
    required String ownerId,
    required String ownerDisplayName,
    required int color,
  }) async {
    _territories = _territories.map((t) {
      if (t.id != territoryId) return t;
      return t.copyWith(
        ownerId: ownerId,
        ownerDisplayName: ownerDisplayName,
        claimedAt: DateTime.now(),
        color: color,
        isContested: false,
        contestedByUid: null,
        contestedAt: null,
      );
    }).toList();
    _emit();
  }

  @override
  Future<void> releaseTerritory(String territoryId) async {
    _territories = _territories.map((t) {
      if (t.id != territoryId) return t;
      return Territory(
        id: t.id,
        name: t.name,
        level: t.level,
        lat: t.lat,
        lng: t.lng,
        radiusMeters: t.radiusMeters,
        parentId: t.parentId,
      );
    }).toList();
    _emit();
  }

  @override
  Future<void> contestTerritory({
    required String territoryId,
    required String challengerUid,
  }) async {
    _territories = _territories.map((t) {
      if (t.id != territoryId) return t;
      return t.copyWith(
        isContested: true,
        contestedByUid: challengerUid,
        contestedAt: DateTime.now(),
      );
    }).toList();
    _emit();
  }

  @override
  Future<void> resolveContest({
    required String territoryId,
    required bool challengerWins,
    String? challengerUid,
    String? challengerDisplayName,
    int? challengerColor,
  }) async {
    _territories = _territories.map((t) {
      if (t.id != territoryId) return t;
      if (challengerWins &&
          challengerUid != null &&
          challengerDisplayName != null) {
        return t.copyWith(
          ownerId: challengerUid,
          ownerDisplayName: challengerDisplayName,
          claimedAt: DateTime.now(),
          color: challengerColor ?? t.color,
          isContested: false,
          contestedByUid: null,
          contestedAt: null,
        );
      }
      return t.copyWith(
        isContested: false,
        contestedByUid: null,
        contestedAt: null,
      );
    }).toList();
    _emit();
  }

  void dispose() => _controller.close();

  /// Sample territories for offline / demo mode.
  /// Hierarchy: neighborhood → city → state → country → continent
  static List<Territory> _defaultTerritories() => [
        // ── Continents ─────────────────────────────────────────────────────
        const Territory(
          id: 'demo_north_america',
          name: 'North America',
          level: TerritoryLevel.continent,
          lat: 54.5260,
          lng: -105.2551,
          radiusMeters: 1200,
        ),
        const Territory(
          id: 'demo_europe',
          name: 'Europe',
          level: TerritoryLevel.continent,
          lat: 54.5260,
          lng: 15.2551,
          radiusMeters: 1200,
        ),
        const Territory(
          id: 'demo_asia',
          name: 'Asia',
          level: TerritoryLevel.continent,
          lat: 34.0479,
          lng: 100.6197,
          radiusMeters: 1200,
        ),
        // ── Countries ──────────────────────────────────────────────────────
        const Territory(
          id: 'demo_usa',
          name: 'United States',
          level: TerritoryLevel.country,
          lat: 37.0902,
          lng: -95.7129,
          radiusMeters: 1000,
          parentId: 'demo_north_america',
        ),
        const Territory(
          id: 'demo_canada',
          name: 'Canada',
          level: TerritoryLevel.country,
          lat: 56.1304,
          lng: -106.3468,
          radiusMeters: 1000,
          parentId: 'demo_north_america',
        ),
        const Territory(
          id: 'demo_uk',
          name: 'United Kingdom',
          level: TerritoryLevel.country,
          lat: 55.3781,
          lng: -3.4360,
          radiusMeters: 1000,
          parentId: 'demo_europe',
        ),
        const Territory(
          id: 'demo_france',
          name: 'France',
          level: TerritoryLevel.country,
          lat: 46.2276,
          lng: 2.2137,
          radiusMeters: 1000,
          parentId: 'demo_europe',
        ),
        const Territory(
          id: 'demo_japan',
          name: 'Japan',
          level: TerritoryLevel.country,
          lat: 36.2048,
          lng: 138.2529,
          radiusMeters: 1000,
          parentId: 'demo_asia',
        ),
        // ── States ─────────────────────────────────────────────────────────
        const Territory(
          id: 'demo_new_york_state',
          name: 'New York State',
          level: TerritoryLevel.state,
          lat: 42.1656,
          lng: -74.9481,
          radiusMeters: 800,
          parentId: 'demo_usa',
        ),
        const Territory(
          id: 'demo_california',
          name: 'California',
          level: TerritoryLevel.state,
          lat: 36.7783,
          lng: -119.4179,
          radiusMeters: 800,
          parentId: 'demo_usa',
        ),
        const Territory(
          id: 'demo_texas',
          name: 'Texas',
          level: TerritoryLevel.state,
          lat: 31.9686,
          lng: -99.9018,
          radiusMeters: 800,
          parentId: 'demo_usa',
        ),
        const Territory(
          id: 'demo_florida',
          name: 'Florida',
          level: TerritoryLevel.state,
          lat: 27.9944,
          lng: -81.7603,
          radiusMeters: 800,
          parentId: 'demo_usa',
        ),
        // ── Cities ─────────────────────────────────────────────────────────
        const Territory(
          id: 'demo_new_york',
          name: 'New York City',
          level: TerritoryLevel.city,
          lat: 40.7128,
          lng: -74.0060,
          radiusMeters: 600,
          parentId: 'demo_new_york_state',
        ),
        const Territory(
          id: 'demo_los_angeles',
          name: 'Los Angeles',
          level: TerritoryLevel.city,
          lat: 34.0522,
          lng: -118.2437,
          radiusMeters: 600,
          parentId: 'demo_california',
        ),
        const Territory(
          id: 'demo_chicago',
          name: 'Chicago',
          level: TerritoryLevel.city,
          lat: 41.8781,
          lng: -87.6298,
          radiusMeters: 600,
          parentId: 'demo_usa',
        ),
        const Territory(
          id: 'demo_miami',
          name: 'Miami',
          level: TerritoryLevel.city,
          lat: 25.7617,
          lng: -80.1918,
          radiusMeters: 600,
          parentId: 'demo_florida',
        ),
        const Territory(
          id: 'demo_houston',
          name: 'Houston',
          level: TerritoryLevel.city,
          lat: 29.7604,
          lng: -95.3698,
          radiusMeters: 600,
          parentId: 'demo_texas',
        ),
        const Territory(
          id: 'demo_london',
          name: 'London',
          level: TerritoryLevel.city,
          lat: 51.5074,
          lng: -0.1278,
          radiusMeters: 600,
          parentId: 'demo_uk',
        ),
        const Territory(
          id: 'demo_paris',
          name: 'Paris',
          level: TerritoryLevel.city,
          lat: 48.8566,
          lng: 2.3522,
          radiusMeters: 600,
          parentId: 'demo_france',
        ),
        const Territory(
          id: 'demo_tokyo',
          name: 'Tokyo',
          level: TerritoryLevel.city,
          lat: 35.6762,
          lng: 139.6503,
          radiusMeters: 600,
          parentId: 'demo_japan',
        ),
        const Territory(
          id: 'demo_toronto',
          name: 'Toronto',
          level: TerritoryLevel.city,
          lat: 43.6532,
          lng: -79.3832,
          radiusMeters: 600,
          parentId: 'demo_canada',
        ),
        // ── NYC Neighborhoods ──────────────────────────────────────────────
        const Territory(
          id: 'demo_times_square',
          name: 'Times Square',
          level: TerritoryLevel.neighborhood,
          lat: 40.7580,
          lng: -73.9855,
          radiusMeters: 120,
          parentId: 'demo_new_york',
        ),
        const Territory(
          id: 'demo_central_park',
          name: 'Central Park',
          level: TerritoryLevel.neighborhood,
          lat: 40.7851,
          lng: -73.9683,
          radiusMeters: 200,
          parentId: 'demo_new_york',
        ),
        const Territory(
          id: 'demo_brooklyn_bridge',
          name: 'Brooklyn Bridge',
          level: TerritoryLevel.neighborhood,
          lat: 40.7061,
          lng: -73.9969,
          radiusMeters: 100,
          parentId: 'demo_new_york',
        ),
        const Territory(
          id: 'demo_wall_street',
          name: 'Wall Street',
          level: TerritoryLevel.neighborhood,
          lat: 40.7074,
          lng: -74.0113,
          radiusMeters: 100,
          parentId: 'demo_new_york',
        ),
        const Territory(
          id: 'demo_soho',
          name: 'SoHo',
          level: TerritoryLevel.neighborhood,
          lat: 40.7233,
          lng: -74.0030,
          radiusMeters: 120,
          parentId: 'demo_new_york',
        ),
        // ── London Neighborhoods ───────────────────────────────────────────
        const Territory(
          id: 'demo_westminster',
          name: 'Westminster',
          level: TerritoryLevel.neighborhood,
          lat: 51.4994,
          lng: -0.1245,
          radiusMeters: 150,
          parentId: 'demo_london',
        ),
        const Territory(
          id: 'demo_shoreditch',
          name: 'Shoreditch',
          level: TerritoryLevel.neighborhood,
          lat: 51.5224,
          lng: -0.0798,
          radiusMeters: 120,
          parentId: 'demo_london',
        ),
        const Territory(
          id: 'demo_canary_wharf',
          name: 'Canary Wharf',
          level: TerritoryLevel.neighborhood,
          lat: 51.5054,
          lng: -0.0235,
          radiusMeters: 130,
          parentId: 'demo_london',
        ),
        // ── Tokyo Neighborhoods ────────────────────────────────────────────
        const Territory(
          id: 'demo_shibuya',
          name: 'Shibuya',
          level: TerritoryLevel.neighborhood,
          lat: 35.6598,
          lng: 139.7004,
          radiusMeters: 150,
          parentId: 'demo_tokyo',
        ),
        const Territory(
          id: 'demo_akihabara',
          name: 'Akihabara',
          level: TerritoryLevel.neighborhood,
          lat: 35.7023,
          lng: 139.7750,
          radiusMeters: 120,
          parentId: 'demo_tokyo',
        ),
        // ── Paris Neighborhoods ────────────────────────────────────────────
        const Territory(
          id: 'demo_montmartre',
          name: 'Montmartre',
          level: TerritoryLevel.neighborhood,
          lat: 48.8867,
          lng: 2.3431,
          radiusMeters: 150,
          parentId: 'demo_paris',
        ),
        const Territory(
          id: 'demo_le_marais',
          name: 'Le Marais',
          level: TerritoryLevel.neighborhood,
          lat: 48.8566,
          lng: 2.3600,
          radiusMeters: 130,
          parentId: 'demo_paris',
        ),

        // ════════════════════════════════════════════════════════════════════
        // +200 TERRITORIES
        // ════════════════════════════════════════════════════════════════════

        // ── New Continents ────────────────────────────────────────────────
        const Territory(
          id: 'demo_south_america',
          name: 'South America',
          level: TerritoryLevel.continent,
          lat: -14.2350,
          lng: -51.9253,
          radiusMeters: 1200,
        ),
        const Territory(
          id: 'demo_africa',
          name: 'Africa',
          level: TerritoryLevel.continent,
          lat: 8.7832,
          lng: 34.5085,
          radiusMeters: 1200,
        ),
        const Territory(
          id: 'demo_oceania',
          name: 'Oceania',
          level: TerritoryLevel.continent,
          lat: -22.7359,
          lng: 140.0188,
          radiusMeters: 1200,
        ),

        // ── New Countries ─────────────────────────────────────────────────
        const Territory(
          id: 'demo_brazil',
          name: 'Brazil',
          level: TerritoryLevel.country,
          lat: -14.2350,
          lng: -51.9253,
          radiusMeters: 1000,
          parentId: 'demo_south_america',
        ),
        const Territory(
          id: 'demo_argentina',
          name: 'Argentina',
          level: TerritoryLevel.country,
          lat: -38.4161,
          lng: -63.6167,
          radiusMeters: 1000,
          parentId: 'demo_south_america',
        ),
        const Territory(
          id: 'demo_colombia',
          name: 'Colombia',
          level: TerritoryLevel.country,
          lat: 4.5709,
          lng: -74.2973,
          radiusMeters: 1000,
          parentId: 'demo_south_america',
        ),
        const Territory(
          id: 'demo_mexico',
          name: 'Mexico',
          level: TerritoryLevel.country,
          lat: 23.6345,
          lng: -102.5528,
          radiusMeters: 1000,
          parentId: 'demo_north_america',
        ),
        const Territory(
          id: 'demo_germany',
          name: 'Germany',
          level: TerritoryLevel.country,
          lat: 51.1657,
          lng: 10.4515,
          radiusMeters: 1000,
          parentId: 'demo_europe',
        ),
        const Territory(
          id: 'demo_spain',
          name: 'Spain',
          level: TerritoryLevel.country,
          lat: 40.4637,
          lng: -3.7492,
          radiusMeters: 1000,
          parentId: 'demo_europe',
        ),
        const Territory(
          id: 'demo_italy',
          name: 'Italy',
          level: TerritoryLevel.country,
          lat: 41.8719,
          lng: 12.5674,
          radiusMeters: 1000,
          parentId: 'demo_europe',
        ),
        const Territory(
          id: 'demo_netherlands',
          name: 'Netherlands',
          level: TerritoryLevel.country,
          lat: 52.1326,
          lng: 5.2913,
          radiusMeters: 1000,
          parentId: 'demo_europe',
        ),
        const Territory(
          id: 'demo_sweden',
          name: 'Sweden',
          level: TerritoryLevel.country,
          lat: 60.1282,
          lng: 18.6435,
          radiusMeters: 1000,
          parentId: 'demo_europe',
        ),
        const Territory(
          id: 'demo_australia',
          name: 'Australia',
          level: TerritoryLevel.country,
          lat: -25.2744,
          lng: 133.7751,
          radiusMeters: 1000,
          parentId: 'demo_oceania',
        ),
        const Territory(
          id: 'demo_china',
          name: 'China',
          level: TerritoryLevel.country,
          lat: 35.8617,
          lng: 104.1954,
          radiusMeters: 1000,
          parentId: 'demo_asia',
        ),
        const Territory(
          id: 'demo_india',
          name: 'India',
          level: TerritoryLevel.country,
          lat: 20.5937,
          lng: 78.9629,
          radiusMeters: 1000,
          parentId: 'demo_asia',
        ),
        const Territory(
          id: 'demo_south_korea',
          name: 'South Korea',
          level: TerritoryLevel.country,
          lat: 35.9078,
          lng: 127.7669,
          radiusMeters: 1000,
          parentId: 'demo_asia',
        ),
        const Territory(
          id: 'demo_nigeria',
          name: 'Nigeria',
          level: TerritoryLevel.country,
          lat: 9.0820,
          lng: 8.6753,
          radiusMeters: 1000,
          parentId: 'demo_africa',
        ),
        const Territory(
          id: 'demo_south_africa',
          name: 'South Africa',
          level: TerritoryLevel.country,
          lat: -30.5595,
          lng: 22.9375,
          radiusMeters: 1000,
          parentId: 'demo_africa',
        ),
        const Territory(
          id: 'demo_egypt',
          name: 'Egypt',
          level: TerritoryLevel.country,
          lat: 26.8206,
          lng: 30.8025,
          radiusMeters: 1000,
          parentId: 'demo_africa',
        ),
        const Territory(
          id: 'demo_turkey',
          name: 'Turkey',
          level: TerritoryLevel.country,
          lat: 38.9637,
          lng: 35.2433,
          radiusMeters: 1000,
          parentId: 'demo_asia',
        ),
        const Territory(
          id: 'demo_indonesia',
          name: 'Indonesia',
          level: TerritoryLevel.country,
          lat: -0.7893,
          lng: 113.9213,
          radiusMeters: 1000,
          parentId: 'demo_asia',
        ),

        // ── New States / Provinces ─────────────────────────────────────────
        const Territory(
          id: 'demo_illinois',
          name: 'Illinois',
          level: TerritoryLevel.state,
          lat: 40.6331,
          lng: -89.3985,
          radiusMeters: 800,
          parentId: 'demo_usa',
        ),
        const Territory(
          id: 'demo_washington_state',
          name: 'Washington State',
          level: TerritoryLevel.state,
          lat: 47.7511,
          lng: -120.7401,
          radiusMeters: 800,
          parentId: 'demo_usa',
        ),
        const Territory(
          id: 'demo_colorado',
          name: 'Colorado',
          level: TerritoryLevel.state,
          lat: 39.5501,
          lng: -105.7821,
          radiusMeters: 800,
          parentId: 'demo_usa',
        ),
        const Territory(
          id: 'demo_georgia_state',
          name: 'Georgia',
          level: TerritoryLevel.state,
          lat: 32.1656,
          lng: -82.9001,
          radiusMeters: 800,
          parentId: 'demo_usa',
        ),
        const Territory(
          id: 'demo_massachusetts',
          name: 'Massachusetts',
          level: TerritoryLevel.state,
          lat: 42.4072,
          lng: -71.3824,
          radiusMeters: 800,
          parentId: 'demo_usa',
        ),
        const Territory(
          id: 'demo_ohio',
          name: 'Ohio',
          level: TerritoryLevel.state,
          lat: 40.4173,
          lng: -82.9071,
          radiusMeters: 800,
          parentId: 'demo_usa',
        ),
        const Territory(
          id: 'demo_pennsylvania',
          name: 'Pennsylvania',
          level: TerritoryLevel.state,
          lat: 41.2033,
          lng: -77.1945,
          radiusMeters: 800,
          parentId: 'demo_usa',
        ),
        const Territory(
          id: 'demo_michigan',
          name: 'Michigan',
          level: TerritoryLevel.state,
          lat: 44.3148,
          lng: -85.6024,
          radiusMeters: 800,
          parentId: 'demo_usa',
        ),
        const Territory(
          id: 'demo_arizona',
          name: 'Arizona',
          level: TerritoryLevel.state,
          lat: 34.0489,
          lng: -111.0937,
          radiusMeters: 800,
          parentId: 'demo_usa',
        ),
        const Territory(
          id: 'demo_nevada',
          name: 'Nevada',
          level: TerritoryLevel.state,
          lat: 38.8026,
          lng: -116.4194,
          radiusMeters: 800,
          parentId: 'demo_usa',
        ),
        const Territory(
          id: 'demo_ontario',
          name: 'Ontario',
          level: TerritoryLevel.state,
          lat: 51.2538,
          lng: -85.3232,
          radiusMeters: 800,
          parentId: 'demo_canada',
        ),
        const Territory(
          id: 'demo_british_columbia',
          name: 'British Columbia',
          level: TerritoryLevel.state,
          lat: 53.7267,
          lng: -127.6476,
          radiusMeters: 800,
          parentId: 'demo_canada',
        ),
        const Territory(
          id: 'demo_quebec',
          name: 'Quebec',
          level: TerritoryLevel.state,
          lat: 52.9399,
          lng: -73.5491,
          radiusMeters: 800,
          parentId: 'demo_canada',
        ),
        const Territory(
          id: 'demo_new_south_wales',
          name: 'New South Wales',
          level: TerritoryLevel.state,
          lat: -31.2532,
          lng: 146.9211,
          radiusMeters: 800,
          parentId: 'demo_australia',
        ),
        const Territory(
          id: 'demo_victoria_state',
          name: 'Victoria',
          level: TerritoryLevel.state,
          lat: -36.5986,
          lng: 144.6780,
          radiusMeters: 800,
          parentId: 'demo_australia',
        ),
        const Territory(
          id: 'demo_bavaria',
          name: 'Bavaria',
          level: TerritoryLevel.state,
          lat: 48.7904,
          lng: 11.4979,
          radiusMeters: 800,
          parentId: 'demo_germany',
        ),
        const Territory(
          id: 'demo_sao_paulo_state',
          name: 'São Paulo State',
          level: TerritoryLevel.state,
          lat: -22.9068,
          lng: -48.4462,
          radiusMeters: 800,
          parentId: 'demo_brazil',
        ),
        const Territory(
          id: 'demo_gauteng',
          name: 'Gauteng',
          level: TerritoryLevel.state,
          lat: -26.2708,
          lng: 28.1123,
          radiusMeters: 800,
          parentId: 'demo_south_africa',
        ),
        const Territory(
          id: 'demo_guangdong',
          name: 'Guangdong',
          level: TerritoryLevel.state,
          lat: 23.3790,
          lng: 113.7633,
          radiusMeters: 800,
          parentId: 'demo_china',
        ),
        const Territory(
          id: 'demo_buenos_aires_province',
          name: 'Buenos Aires Province',
          level: TerritoryLevel.state,
          lat: -36.6769,
          lng: -60.5588,
          radiusMeters: 800,
          parentId: 'demo_argentina',
        ),

        // ── New Cities ────────────────────────────────────────────────────
        const Territory(
          id: 'demo_seattle',
          name: 'Seattle',
          level: TerritoryLevel.city,
          lat: 47.6062,
          lng: -122.3321,
          radiusMeters: 600,
          parentId: 'demo_washington_state',
        ),
        const Territory(
          id: 'demo_denver',
          name: 'Denver',
          level: TerritoryLevel.city,
          lat: 39.7392,
          lng: -104.9903,
          radiusMeters: 600,
          parentId: 'demo_colorado',
        ),
        const Territory(
          id: 'demo_atlanta',
          name: 'Atlanta',
          level: TerritoryLevel.city,
          lat: 33.7490,
          lng: -84.3880,
          radiusMeters: 600,
          parentId: 'demo_georgia_state',
        ),
        const Territory(
          id: 'demo_boston',
          name: 'Boston',
          level: TerritoryLevel.city,
          lat: 42.3601,
          lng: -71.0589,
          radiusMeters: 600,
          parentId: 'demo_massachusetts',
        ),
        const Territory(
          id: 'demo_philadelphia',
          name: 'Philadelphia',
          level: TerritoryLevel.city,
          lat: 39.9526,
          lng: -75.1652,
          radiusMeters: 600,
          parentId: 'demo_pennsylvania',
        ),
        const Territory(
          id: 'demo_phoenix',
          name: 'Phoenix',
          level: TerritoryLevel.city,
          lat: 33.4484,
          lng: -112.0740,
          radiusMeters: 600,
          parentId: 'demo_arizona',
        ),
        const Territory(
          id: 'demo_las_vegas',
          name: 'Las Vegas',
          level: TerritoryLevel.city,
          lat: 36.1699,
          lng: -115.1398,
          radiusMeters: 600,
          parentId: 'demo_nevada',
        ),
        const Territory(
          id: 'demo_detroit',
          name: 'Detroit',
          level: TerritoryLevel.city,
          lat: 42.3314,
          lng: -83.0458,
          radiusMeters: 600,
          parentId: 'demo_michigan',
        ),
        const Territory(
          id: 'demo_columbus',
          name: 'Columbus',
          level: TerritoryLevel.city,
          lat: 39.9612,
          lng: -82.9988,
          radiusMeters: 600,
          parentId: 'demo_ohio',
        ),
        const Territory(
          id: 'demo_philadelphia_pa',
          name: 'Pittsburgh',
          level: TerritoryLevel.city,
          lat: 40.4406,
          lng: -79.9959,
          radiusMeters: 600,
          parentId: 'demo_pennsylvania',
        ),
        const Territory(
          id: 'demo_vancouver',
          name: 'Vancouver',
          level: TerritoryLevel.city,
          lat: 49.2827,
          lng: -123.1207,
          radiusMeters: 600,
          parentId: 'demo_british_columbia',
        ),
        const Territory(
          id: 'demo_montreal',
          name: 'Montreal',
          level: TerritoryLevel.city,
          lat: 45.5017,
          lng: -73.5673,
          radiusMeters: 600,
          parentId: 'demo_quebec',
        ),
        const Territory(
          id: 'demo_sydney',
          name: 'Sydney',
          level: TerritoryLevel.city,
          lat: -33.8688,
          lng: 151.2093,
          radiusMeters: 600,
          parentId: 'demo_new_south_wales',
        ),
        const Territory(
          id: 'demo_melbourne',
          name: 'Melbourne',
          level: TerritoryLevel.city,
          lat: -37.8136,
          lng: 144.9631,
          radiusMeters: 600,
          parentId: 'demo_victoria_state',
        ),
        const Territory(
          id: 'demo_munich',
          name: 'Munich',
          level: TerritoryLevel.city,
          lat: 48.1351,
          lng: 11.5820,
          radiusMeters: 600,
          parentId: 'demo_bavaria',
        ),
        const Territory(
          id: 'demo_berlin',
          name: 'Berlin',
          level: TerritoryLevel.city,
          lat: 52.5200,
          lng: 13.4050,
          radiusMeters: 600,
          parentId: 'demo_germany',
        ),
        const Territory(
          id: 'demo_madrid',
          name: 'Madrid',
          level: TerritoryLevel.city,
          lat: 40.4168,
          lng: -3.7038,
          radiusMeters: 600,
          parentId: 'demo_spain',
        ),
        const Territory(
          id: 'demo_barcelona',
          name: 'Barcelona',
          level: TerritoryLevel.city,
          lat: 41.3851,
          lng: 2.1734,
          radiusMeters: 600,
          parentId: 'demo_spain',
        ),
        const Territory(
          id: 'demo_rome',
          name: 'Rome',
          level: TerritoryLevel.city,
          lat: 41.9028,
          lng: 12.4964,
          radiusMeters: 600,
          parentId: 'demo_italy',
        ),
        const Territory(
          id: 'demo_milan',
          name: 'Milan',
          level: TerritoryLevel.city,
          lat: 45.4642,
          lng: 9.1900,
          radiusMeters: 600,
          parentId: 'demo_italy',
        ),
        const Territory(
          id: 'demo_amsterdam',
          name: 'Amsterdam',
          level: TerritoryLevel.city,
          lat: 52.3676,
          lng: 4.9041,
          radiusMeters: 600,
          parentId: 'demo_netherlands',
        ),
        const Territory(
          id: 'demo_stockholm',
          name: 'Stockholm',
          level: TerritoryLevel.city,
          lat: 59.3293,
          lng: 18.0686,
          radiusMeters: 600,
          parentId: 'demo_sweden',
        ),
        const Territory(
          id: 'demo_sao_paulo',
          name: 'São Paulo',
          level: TerritoryLevel.city,
          lat: -23.5505,
          lng: -46.6333,
          radiusMeters: 600,
          parentId: 'demo_sao_paulo_state',
        ),
        const Territory(
          id: 'demo_rio',
          name: 'Rio de Janeiro',
          level: TerritoryLevel.city,
          lat: -22.9068,
          lng: -43.1729,
          radiusMeters: 600,
          parentId: 'demo_brazil',
        ),
        const Territory(
          id: 'demo_mexico_city',
          name: 'Mexico City',
          level: TerritoryLevel.city,
          lat: 19.4326,
          lng: -99.1332,
          radiusMeters: 600,
          parentId: 'demo_mexico',
        ),
        const Territory(
          id: 'demo_buenos_aires',
          name: 'Buenos Aires',
          level: TerritoryLevel.city,
          lat: -34.6037,
          lng: -58.3816,
          radiusMeters: 600,
          parentId: 'demo_buenos_aires_province',
        ),
        const Territory(
          id: 'demo_bogota',
          name: 'Bogotá',
          level: TerritoryLevel.city,
          lat: 4.7110,
          lng: -74.0721,
          radiusMeters: 600,
          parentId: 'demo_colombia',
        ),
        const Territory(
          id: 'demo_lagos',
          name: 'Lagos',
          level: TerritoryLevel.city,
          lat: 6.5244,
          lng: 3.3792,
          radiusMeters: 600,
          parentId: 'demo_nigeria',
        ),
        const Territory(
          id: 'demo_cape_town',
          name: 'Cape Town',
          level: TerritoryLevel.city,
          lat: -33.9249,
          lng: 18.4241,
          radiusMeters: 600,
          parentId: 'demo_south_africa',
        ),
        const Territory(
          id: 'demo_johannesburg',
          name: 'Johannesburg',
          level: TerritoryLevel.city,
          lat: -26.2041,
          lng: 28.0473,
          radiusMeters: 600,
          parentId: 'demo_gauteng',
        ),
        const Territory(
          id: 'demo_cairo',
          name: 'Cairo',
          level: TerritoryLevel.city,
          lat: 30.0444,
          lng: 31.2357,
          radiusMeters: 600,
          parentId: 'demo_egypt',
        ),
        const Territory(
          id: 'demo_nairobi',
          name: 'Nairobi',
          level: TerritoryLevel.city,
          lat: -1.2921,
          lng: 36.8219,
          radiusMeters: 600,
          parentId: 'demo_africa',
        ),
        const Territory(
          id: 'demo_mumbai',
          name: 'Mumbai',
          level: TerritoryLevel.city,
          lat: 19.0760,
          lng: 72.8777,
          radiusMeters: 600,
          parentId: 'demo_india',
        ),
        const Territory(
          id: 'demo_delhi',
          name: 'New Delhi',
          level: TerritoryLevel.city,
          lat: 28.6139,
          lng: 77.2090,
          radiusMeters: 600,
          parentId: 'demo_india',
        ),
        const Territory(
          id: 'demo_bangalore',
          name: 'Bangalore',
          level: TerritoryLevel.city,
          lat: 12.9716,
          lng: 77.5946,
          radiusMeters: 600,
          parentId: 'demo_india',
        ),
        const Territory(
          id: 'demo_seoul',
          name: 'Seoul',
          level: TerritoryLevel.city,
          lat: 37.5665,
          lng: 126.9780,
          radiusMeters: 600,
          parentId: 'demo_south_korea',
        ),
        const Territory(
          id: 'demo_beijing',
          name: 'Beijing',
          level: TerritoryLevel.city,
          lat: 39.9042,
          lng: 116.4074,
          radiusMeters: 600,
          parentId: 'demo_china',
        ),
        const Territory(
          id: 'demo_shanghai',
          name: 'Shanghai',
          level: TerritoryLevel.city,
          lat: 31.2304,
          lng: 121.4737,
          radiusMeters: 600,
          parentId: 'demo_china',
        ),
        const Territory(
          id: 'demo_guangzhou',
          name: 'Guangzhou',
          level: TerritoryLevel.city,
          lat: 23.1291,
          lng: 113.2644,
          radiusMeters: 600,
          parentId: 'demo_guangdong',
        ),
        const Territory(
          id: 'demo_singapore',
          name: 'Singapore',
          level: TerritoryLevel.city,
          lat: 1.3521,
          lng: 103.8198,
          radiusMeters: 600,
          parentId: 'demo_asia',
        ),
        const Territory(
          id: 'demo_dubai',
          name: 'Dubai',
          level: TerritoryLevel.city,
          lat: 25.2048,
          lng: 55.2708,
          radiusMeters: 600,
          parentId: 'demo_asia',
        ),
        const Territory(
          id: 'demo_istanbul',
          name: 'Istanbul',
          level: TerritoryLevel.city,
          lat: 41.0082,
          lng: 28.9784,
          radiusMeters: 600,
          parentId: 'demo_turkey',
        ),
        const Territory(
          id: 'demo_osaka',
          name: 'Osaka',
          level: TerritoryLevel.city,
          lat: 34.6937,
          lng: 135.5023,
          radiusMeters: 600,
          parentId: 'demo_japan',
        ),
        const Territory(
          id: 'demo_kyoto',
          name: 'Kyoto',
          level: TerritoryLevel.city,
          lat: 35.0116,
          lng: 135.7681,
          radiusMeters: 600,
          parentId: 'demo_japan',
        ),
        const Territory(
          id: 'demo_bangkok',
          name: 'Bangkok',
          level: TerritoryLevel.city,
          lat: 13.7563,
          lng: 100.5018,
          radiusMeters: 600,
          parentId: 'demo_asia',
        ),
        const Territory(
          id: 'demo_jakarta',
          name: 'Jakarta',
          level: TerritoryLevel.city,
          lat: -6.2088,
          lng: 106.8456,
          radiusMeters: 600,
          parentId: 'demo_indonesia',
        ),
        const Territory(
          id: 'demo_kuala_lumpur',
          name: 'Kuala Lumpur',
          level: TerritoryLevel.city,
          lat: 3.1390,
          lng: 101.6869,
          radiusMeters: 600,
          parentId: 'demo_asia',
        ),

        // ── NYC – extra neighborhoods ─────────────────────────────────────
        const Territory(
          id: 'demo_williamsburg',
          name: 'Williamsburg',
          level: TerritoryLevel.neighborhood,
          lat: 40.7081,
          lng: -73.9571,
          radiusMeters: 120,
          parentId: 'demo_new_york',
        ),
        const Territory(
          id: 'demo_east_village',
          name: 'East Village',
          level: TerritoryLevel.neighborhood,
          lat: 40.7265,
          lng: -73.9815,
          radiusMeters: 110,
          parentId: 'demo_new_york',
        ),
        const Territory(
          id: 'demo_harlem',
          name: 'Harlem',
          level: TerritoryLevel.neighborhood,
          lat: 40.8116,
          lng: -73.9465,
          radiusMeters: 130,
          parentId: 'demo_new_york',
        ),
        const Territory(
          id: 'demo_astoria',
          name: 'Astoria',
          level: TerritoryLevel.neighborhood,
          lat: 40.7721,
          lng: -73.9301,
          radiusMeters: 120,
          parentId: 'demo_new_york',
        ),

        // ── LA – neighborhoods ────────────────────────────────────────────
        const Territory(
          id: 'demo_venice_beach',
          name: 'Venice Beach',
          level: TerritoryLevel.neighborhood,
          lat: 33.9850,
          lng: -118.4695,
          radiusMeters: 130,
          parentId: 'demo_los_angeles',
        ),
        const Territory(
          id: 'demo_hollywood',
          name: 'Hollywood',
          level: TerritoryLevel.neighborhood,
          lat: 34.0928,
          lng: -118.3287,
          radiusMeters: 140,
          parentId: 'demo_los_angeles',
        ),
        const Territory(
          id: 'demo_koreatown_la',
          name: 'Koreatown',
          level: TerritoryLevel.neighborhood,
          lat: 34.0595,
          lng: -118.3,
          radiusMeters: 120,
          parentId: 'demo_los_angeles',
        ),
        const Territory(
          id: 'demo_beverly_hills',
          name: 'Beverly Hills',
          level: TerritoryLevel.neighborhood,
          lat: 34.0736,
          lng: -118.4004,
          radiusMeters: 130,
          parentId: 'demo_los_angeles',
        ),

        // ── Chicago – neighborhoods ───────────────────────────────────────
        const Territory(
          id: 'demo_wicker_park',
          name: 'Wicker Park',
          level: TerritoryLevel.neighborhood,
          lat: 41.9088,
          lng: -87.6772,
          radiusMeters: 120,
          parentId: 'demo_chicago',
        ),
        const Territory(
          id: 'demo_the_loop',
          name: 'The Loop',
          level: TerritoryLevel.neighborhood,
          lat: 41.8827,
          lng: -87.6278,
          radiusMeters: 130,
          parentId: 'demo_chicago',
        ),
        const Territory(
          id: 'demo_lincoln_park',
          name: 'Lincoln Park',
          level: TerritoryLevel.neighborhood,
          lat: 41.9214,
          lng: -87.6513,
          radiusMeters: 140,
          parentId: 'demo_chicago',
        ),
        const Territory(
          id: 'demo_pilsen',
          name: 'Pilsen',
          level: TerritoryLevel.neighborhood,
          lat: 41.8563,
          lng: -87.6596,
          radiusMeters: 120,
          parentId: 'demo_chicago',
        ),

        // ── Seattle – neighborhoods ───────────────────────────────────────
        const Territory(
          id: 'demo_capitol_hill_sea',
          name: 'Capitol Hill',
          level: TerritoryLevel.neighborhood,
          lat: 47.6237,
          lng: -122.3201,
          radiusMeters: 120,
          parentId: 'demo_seattle',
        ),
        const Territory(
          id: 'demo_fremont_sea',
          name: 'Fremont',
          level: TerritoryLevel.neighborhood,
          lat: 47.6508,
          lng: -122.3501,
          radiusMeters: 110,
          parentId: 'demo_seattle',
        ),
        const Territory(
          id: 'demo_ballard',
          name: 'Ballard',
          level: TerritoryLevel.neighborhood,
          lat: 47.6681,
          lng: -122.3834,
          radiusMeters: 120,
          parentId: 'demo_seattle',
        ),
        const Territory(
          id: 'demo_pike_place',
          name: 'Pike Place Market',
          level: TerritoryLevel.neighborhood,
          lat: 47.6097,
          lng: -122.3422,
          radiusMeters: 100,
          parentId: 'demo_seattle',
        ),

        // ── Denver – neighborhoods ────────────────────────────────────────
        const Territory(
          id: 'demo_lodo',
          name: 'LoDo',
          level: TerritoryLevel.neighborhood,
          lat: 39.7527,
          lng: -104.9997,
          radiusMeters: 110,
          parentId: 'demo_denver',
        ),
        const Territory(
          id: 'demo_rino',
          name: 'RiNo',
          level: TerritoryLevel.neighborhood,
          lat: 39.7678,
          lng: -104.9809,
          radiusMeters: 120,
          parentId: 'demo_denver',
        ),
        const Territory(
          id: 'demo_cherry_creek',
          name: 'Cherry Creek',
          level: TerritoryLevel.neighborhood,
          lat: 39.7194,
          lng: -104.9568,
          radiusMeters: 120,
          parentId: 'demo_denver',
        ),

        // ── Boston – neighborhoods ────────────────────────────────────────
        const Territory(
          id: 'demo_beacon_hill',
          name: 'Beacon Hill',
          level: TerritoryLevel.neighborhood,
          lat: 42.3588,
          lng: -71.0707,
          radiusMeters: 110,
          parentId: 'demo_boston',
        ),
        const Territory(
          id: 'demo_back_bay',
          name: 'Back Bay',
          level: TerritoryLevel.neighborhood,
          lat: 42.3501,
          lng: -71.0810,
          radiusMeters: 120,
          parentId: 'demo_boston',
        ),
        const Territory(
          id: 'demo_south_end_boston',
          name: 'South End',
          level: TerritoryLevel.neighborhood,
          lat: 42.3417,
          lng: -71.0738,
          radiusMeters: 120,
          parentId: 'demo_boston',
        ),
        const Territory(
          id: 'demo_fenway',
          name: 'Fenway',
          level: TerritoryLevel.neighborhood,
          lat: 42.3467,
          lng: -71.0972,
          radiusMeters: 110,
          parentId: 'demo_boston',
        ),

        // ── Las Vegas – neighborhoods ─────────────────────────────────────
        const Territory(
          id: 'demo_the_strip',
          name: 'The Strip',
          level: TerritoryLevel.neighborhood,
          lat: 36.1147,
          lng: -115.1728,
          radiusMeters: 150,
          parentId: 'demo_las_vegas',
        ),
        const Territory(
          id: 'demo_fremont_street',
          name: 'Fremont Street',
          level: TerritoryLevel.neighborhood,
          lat: 36.1713,
          lng: -115.1440,
          radiusMeters: 110,
          parentId: 'demo_las_vegas',
        ),
        const Territory(
          id: 'demo_summerlin',
          name: 'Summerlin',
          level: TerritoryLevel.neighborhood,
          lat: 36.1716,
          lng: -115.3254,
          radiusMeters: 130,
          parentId: 'demo_las_vegas',
        ),

        // ── London – extra neighborhoods ──────────────────────────────────
        const Territory(
          id: 'demo_brixton',
          name: 'Brixton',
          level: TerritoryLevel.neighborhood,
          lat: 51.4613,
          lng: -0.1156,
          radiusMeters: 120,
          parentId: 'demo_london',
        ),
        const Territory(
          id: 'demo_soho_london',
          name: 'Soho',
          level: TerritoryLevel.neighborhood,
          lat: 51.5131,
          lng: -0.1363,
          radiusMeters: 110,
          parentId: 'demo_london',
        ),
        const Territory(
          id: 'demo_notting_hill',
          name: 'Notting Hill',
          level: TerritoryLevel.neighborhood,
          lat: 51.5092,
          lng: -0.2087,
          radiusMeters: 120,
          parentId: 'demo_london',
        ),
        const Territory(
          id: 'demo_hackney',
          name: 'Hackney',
          level: TerritoryLevel.neighborhood,
          lat: 51.5450,
          lng: -0.0553,
          radiusMeters: 130,
          parentId: 'demo_london',
        ),

        // ── Paris – extra neighborhoods ───────────────────────────────────
        const Territory(
          id: 'demo_bastille',
          name: 'Bastille',
          level: TerritoryLevel.neighborhood,
          lat: 48.8533,
          lng: 2.3692,
          radiusMeters: 110,
          parentId: 'demo_paris',
        ),
        const Territory(
          id: 'demo_belleville',
          name: 'Belleville',
          level: TerritoryLevel.neighborhood,
          lat: 48.8699,
          lng: 2.3842,
          radiusMeters: 120,
          parentId: 'demo_paris',
        ),
        const Territory(
          id: 'demo_saint_germain',
          name: 'Saint-Germain',
          level: TerritoryLevel.neighborhood,
          lat: 48.8540,
          lng: 2.3330,
          radiusMeters: 120,
          parentId: 'demo_paris',
        ),

        // ── Sydney – neighborhoods ────────────────────────────────────────
        const Territory(
          id: 'demo_the_rocks_syd',
          name: 'The Rocks',
          level: TerritoryLevel.neighborhood,
          lat: -33.8599,
          lng: 151.2090,
          radiusMeters: 110,
          parentId: 'demo_sydney',
        ),
        const Territory(
          id: 'demo_bondi_beach',
          name: 'Bondi Beach',
          level: TerritoryLevel.neighborhood,
          lat: -33.8915,
          lng: 151.2767,
          radiusMeters: 130,
          parentId: 'demo_sydney',
        ),
        const Territory(
          id: 'demo_surry_hills',
          name: 'Surry Hills',
          level: TerritoryLevel.neighborhood,
          lat: -33.8860,
          lng: 151.2094,
          radiusMeters: 120,
          parentId: 'demo_sydney',
        ),
        const Territory(
          id: 'demo_newtown_syd',
          name: 'Newtown',
          level: TerritoryLevel.neighborhood,
          lat: -33.8977,
          lng: 151.1796,
          radiusMeters: 120,
          parentId: 'demo_sydney',
        ),
        const Territory(
          id: 'demo_manly',
          name: 'Manly',
          level: TerritoryLevel.neighborhood,
          lat: -33.7969,
          lng: 151.2855,
          radiusMeters: 130,
          parentId: 'demo_sydney',
        ),

        // ── Melbourne – neighborhoods ─────────────────────────────────────
        const Territory(
          id: 'demo_fitzroy',
          name: 'Fitzroy',
          level: TerritoryLevel.neighborhood,
          lat: -37.7997,
          lng: 144.9781,
          radiusMeters: 120,
          parentId: 'demo_melbourne',
        ),
        const Territory(
          id: 'demo_st_kilda',
          name: 'St Kilda',
          level: TerritoryLevel.neighborhood,
          lat: -37.8676,
          lng: 144.9780,
          radiusMeters: 130,
          parentId: 'demo_melbourne',
        ),
        const Territory(
          id: 'demo_southbank_melb',
          name: 'Southbank',
          level: TerritoryLevel.neighborhood,
          lat: -37.8224,
          lng: 144.9646,
          radiusMeters: 120,
          parentId: 'demo_melbourne',
        ),
        const Territory(
          id: 'demo_collingwood',
          name: 'Collingwood',
          level: TerritoryLevel.neighborhood,
          lat: -37.8025,
          lng: 144.9930,
          radiusMeters: 120,
          parentId: 'demo_melbourne',
        ),

        // ── Berlin – neighborhoods ────────────────────────────────────────
        const Territory(
          id: 'demo_mitte',
          name: 'Mitte',
          level: TerritoryLevel.neighborhood,
          lat: 52.5244,
          lng: 13.4105,
          radiusMeters: 140,
          parentId: 'demo_berlin',
        ),
        const Territory(
          id: 'demo_kreuzberg',
          name: 'Kreuzberg',
          level: TerritoryLevel.neighborhood,
          lat: 52.4987,
          lng: 13.4028,
          radiusMeters: 130,
          parentId: 'demo_berlin',
        ),
        const Territory(
          id: 'demo_prenzlauer_berg',
          name: 'Prenzlauer Berg',
          level: TerritoryLevel.neighborhood,
          lat: 52.5389,
          lng: 13.4244,
          radiusMeters: 130,
          parentId: 'demo_berlin',
        ),
        const Territory(
          id: 'demo_friedrichshain',
          name: 'Friedrichshain',
          level: TerritoryLevel.neighborhood,
          lat: 52.5136,
          lng: 13.4545,
          radiusMeters: 130,
          parentId: 'demo_berlin',
        ),

        // ── Munich – neighborhoods ────────────────────────────────────────
        const Territory(
          id: 'demo_marienplatz',
          name: 'Marienplatz',
          level: TerritoryLevel.neighborhood,
          lat: 48.1374,
          lng: 11.5755,
          radiusMeters: 100,
          parentId: 'demo_munich',
        ),
        const Territory(
          id: 'demo_schwabing',
          name: 'Schwabing',
          level: TerritoryLevel.neighborhood,
          lat: 48.1591,
          lng: 11.5820,
          radiusMeters: 130,
          parentId: 'demo_munich',
        ),
        const Territory(
          id: 'demo_maxvorstadt',
          name: 'Maxvorstadt',
          level: TerritoryLevel.neighborhood,
          lat: 48.1498,
          lng: 11.5680,
          radiusMeters: 120,
          parentId: 'demo_munich',
        ),

        // ── Madrid – neighborhoods ────────────────────────────────────────
        const Territory(
          id: 'demo_malasana',
          name: 'Malasaña',
          level: TerritoryLevel.neighborhood,
          lat: 40.4248,
          lng: -3.7048,
          radiusMeters: 120,
          parentId: 'demo_madrid',
        ),
        const Territory(
          id: 'demo_lavapies',
          name: 'Lavapiés',
          level: TerritoryLevel.neighborhood,
          lat: 40.4108,
          lng: -3.7021,
          radiusMeters: 110,
          parentId: 'demo_madrid',
        ),
        const Territory(
          id: 'demo_salamanca_dist',
          name: 'Salamanca',
          level: TerritoryLevel.neighborhood,
          lat: 40.4250,
          lng: -3.6832,
          radiusMeters: 130,
          parentId: 'demo_madrid',
        ),
        const Territory(
          id: 'demo_la_latina',
          name: 'La Latina',
          level: TerritoryLevel.neighborhood,
          lat: 40.4131,
          lng: -3.7102,
          radiusMeters: 110,
          parentId: 'demo_madrid',
        ),

        // ── Barcelona – neighborhoods ─────────────────────────────────────
        const Territory(
          id: 'demo_gotic',
          name: 'Barri Gòtic',
          level: TerritoryLevel.neighborhood,
          lat: 41.3825,
          lng: 2.1769,
          radiusMeters: 110,
          parentId: 'demo_barcelona',
        ),
        const Territory(
          id: 'demo_eixample',
          name: 'Eixample',
          level: TerritoryLevel.neighborhood,
          lat: 41.3927,
          lng: 2.1608,
          radiusMeters: 150,
          parentId: 'demo_barcelona',
        ),
        const Territory(
          id: 'demo_gracia',
          name: 'Gràcia',
          level: TerritoryLevel.neighborhood,
          lat: 41.4033,
          lng: 2.1563,
          radiusMeters: 130,
          parentId: 'demo_barcelona',
        ),
        const Territory(
          id: 'demo_poblenou',
          name: 'Poblenou',
          level: TerritoryLevel.neighborhood,
          lat: 41.4027,
          lng: 2.2050,
          radiusMeters: 130,
          parentId: 'demo_barcelona',
        ),

        // ── Rome – neighborhoods ──────────────────────────────────────────
        const Territory(
          id: 'demo_trastevere',
          name: 'Trastevere',
          level: TerritoryLevel.neighborhood,
          lat: 41.8896,
          lng: 12.4701,
          radiusMeters: 120,
          parentId: 'demo_rome',
        ),
        const Territory(
          id: 'demo_prati',
          name: 'Prati',
          level: TerritoryLevel.neighborhood,
          lat: 41.9047,
          lng: 12.4607,
          radiusMeters: 120,
          parentId: 'demo_rome',
        ),
        const Territory(
          id: 'demo_testaccio',
          name: 'Testaccio',
          level: TerritoryLevel.neighborhood,
          lat: 41.8803,
          lng: 12.4765,
          radiusMeters: 110,
          parentId: 'demo_rome',
        ),

        // ── Amsterdam – neighborhoods ─────────────────────────────────────
        const Territory(
          id: 'demo_jordaan',
          name: 'Jordaan',
          level: TerritoryLevel.neighborhood,
          lat: 52.3738,
          lng: 4.8826,
          radiusMeters: 120,
          parentId: 'demo_amsterdam',
        ),
        const Territory(
          id: 'demo_de_pijp',
          name: 'De Pijp',
          level: TerritoryLevel.neighborhood,
          lat: 52.3531,
          lng: 4.8977,
          radiusMeters: 120,
          parentId: 'demo_amsterdam',
        ),
        const Territory(
          id: 'demo_oud_west',
          name: 'Oud-West',
          level: TerritoryLevel.neighborhood,
          lat: 52.3651,
          lng: 4.8737,
          radiusMeters: 120,
          parentId: 'demo_amsterdam',
        ),

        // ── São Paulo – neighborhoods ─────────────────────────────────────
        const Territory(
          id: 'demo_vila_madalena',
          name: 'Vila Madalena',
          level: TerritoryLevel.neighborhood,
          lat: -23.5551,
          lng: -46.6886,
          radiusMeters: 120,
          parentId: 'demo_sao_paulo',
        ),
        const Territory(
          id: 'demo_pinheiros',
          name: 'Pinheiros',
          level: TerritoryLevel.neighborhood,
          lat: -23.5647,
          lng: -46.6931,
          radiusMeters: 130,
          parentId: 'demo_sao_paulo',
        ),
        const Territory(
          id: 'demo_jardins',
          name: 'Jardins',
          level: TerritoryLevel.neighborhood,
          lat: -23.5713,
          lng: -46.6568,
          radiusMeters: 130,
          parentId: 'demo_sao_paulo',
        ),
        const Territory(
          id: 'demo_moema',
          name: 'Moema',
          level: TerritoryLevel.neighborhood,
          lat: -23.6009,
          lng: -46.6647,
          radiusMeters: 120,
          parentId: 'demo_sao_paulo',
        ),

        // ── Mexico City – neighborhoods ───────────────────────────────────
        const Territory(
          id: 'demo_roma_norte',
          name: 'Roma Norte',
          level: TerritoryLevel.neighborhood,
          lat: 19.4193,
          lng: -99.1592,
          radiusMeters: 130,
          parentId: 'demo_mexico_city',
        ),
        const Territory(
          id: 'demo_condesa',
          name: 'La Condesa',
          level: TerritoryLevel.neighborhood,
          lat: 19.4133,
          lng: -99.1745,
          radiusMeters: 120,
          parentId: 'demo_mexico_city',
        ),
        const Territory(
          id: 'demo_polanco',
          name: 'Polanco',
          level: TerritoryLevel.neighborhood,
          lat: 19.4330,
          lng: -99.1952,
          radiusMeters: 140,
          parentId: 'demo_mexico_city',
        ),
        const Territory(
          id: 'demo_coyoacan',
          name: 'Coyoacán',
          level: TerritoryLevel.neighborhood,
          lat: 19.3500,
          lng: -99.1616,
          radiusMeters: 150,
          parentId: 'demo_mexico_city',
        ),

        // ── Buenos Aires – neighborhoods ──────────────────────────────────
        const Territory(
          id: 'demo_palermo',
          name: 'Palermo',
          level: TerritoryLevel.neighborhood,
          lat: -34.5832,
          lng: -58.4253,
          radiusMeters: 150,
          parentId: 'demo_buenos_aires',
        ),
        const Territory(
          id: 'demo_san_telmo',
          name: 'San Telmo',
          level: TerritoryLevel.neighborhood,
          lat: -34.6197,
          lng: -58.3731,
          radiusMeters: 120,
          parentId: 'demo_buenos_aires',
        ),
        const Territory(
          id: 'demo_recoleta',
          name: 'Recoleta',
          level: TerritoryLevel.neighborhood,
          lat: -34.5893,
          lng: -58.3930,
          radiusMeters: 130,
          parentId: 'demo_buenos_aires',
        ),
        const Territory(
          id: 'demo_la_boca',
          name: 'La Boca',
          level: TerritoryLevel.neighborhood,
          lat: -34.6345,
          lng: -58.3631,
          radiusMeters: 120,
          parentId: 'demo_buenos_aires',
        ),

        // ── Seoul – neighborhoods ─────────────────────────────────────────
        const Territory(
          id: 'demo_gangnam',
          name: 'Gangnam',
          level: TerritoryLevel.neighborhood,
          lat: 37.5172,
          lng: 127.0473,
          radiusMeters: 150,
          parentId: 'demo_seoul',
        ),
        const Territory(
          id: 'demo_itaewon',
          name: 'Itaewon',
          level: TerritoryLevel.neighborhood,
          lat: 37.5340,
          lng: 126.9938,
          radiusMeters: 120,
          parentId: 'demo_seoul',
        ),
        const Territory(
          id: 'demo_hongdae',
          name: 'Hongdae',
          level: TerritoryLevel.neighborhood,
          lat: 37.5563,
          lng: 126.9239,
          radiusMeters: 120,
          parentId: 'demo_seoul',
        ),
        const Territory(
          id: 'demo_insadong',
          name: 'Insadong',
          level: TerritoryLevel.neighborhood,
          lat: 37.5741,
          lng: 126.9844,
          radiusMeters: 110,
          parentId: 'demo_seoul',
        ),

        // ── Osaka – neighborhoods ─────────────────────────────────────────
        const Territory(
          id: 'demo_dotonbori',
          name: 'Dotonbori',
          level: TerritoryLevel.neighborhood,
          lat: 34.6687,
          lng: 135.5015,
          radiusMeters: 110,
          parentId: 'demo_osaka',
        ),
        const Territory(
          id: 'demo_namba',
          name: 'Namba',
          level: TerritoryLevel.neighborhood,
          lat: 34.6641,
          lng: 135.5007,
          radiusMeters: 110,
          parentId: 'demo_osaka',
        ),
        const Territory(
          id: 'demo_umeda',
          name: 'Umeda',
          level: TerritoryLevel.neighborhood,
          lat: 34.7024,
          lng: 135.4980,
          radiusMeters: 120,
          parentId: 'demo_osaka',
        ),

        // ── Singapore – neighborhoods ─────────────────────────────────────
        const Territory(
          id: 'demo_marina_bay',
          name: 'Marina Bay',
          level: TerritoryLevel.neighborhood,
          lat: 1.2789,
          lng: 103.8536,
          radiusMeters: 130,
          parentId: 'demo_singapore',
        ),
        const Territory(
          id: 'demo_chinatown_sg',
          name: 'Chinatown',
          level: TerritoryLevel.neighborhood,
          lat: 1.2831,
          lng: 103.8448,
          radiusMeters: 120,
          parentId: 'demo_singapore',
        ),
        const Territory(
          id: 'demo_little_india_sg',
          name: 'Little India',
          level: TerritoryLevel.neighborhood,
          lat: 1.3065,
          lng: 103.8519,
          radiusMeters: 110,
          parentId: 'demo_singapore',
        ),

        // ── Dubai – neighborhoods ─────────────────────────────────────────
        const Territory(
          id: 'demo_downtown_dubai',
          name: 'Downtown Dubai',
          level: TerritoryLevel.neighborhood,
          lat: 25.1972,
          lng: 55.2744,
          radiusMeters: 140,
          parentId: 'demo_dubai',
        ),
        const Territory(
          id: 'demo_dubai_marina',
          name: 'Dubai Marina',
          level: TerritoryLevel.neighborhood,
          lat: 25.0797,
          lng: 55.1404,
          radiusMeters: 150,
          parentId: 'demo_dubai',
        ),
        const Territory(
          id: 'demo_deira',
          name: 'Deira',
          level: TerritoryLevel.neighborhood,
          lat: 25.2697,
          lng: 55.3095,
          radiusMeters: 130,
          parentId: 'demo_dubai',
        ),

        // ── Istanbul – neighborhoods ──────────────────────────────────────
        const Territory(
          id: 'demo_beyoglu',
          name: 'Beyoğlu',
          level: TerritoryLevel.neighborhood,
          lat: 41.0311,
          lng: 28.9775,
          radiusMeters: 130,
          parentId: 'demo_istanbul',
        ),
        const Territory(
          id: 'demo_kadikoy',
          name: 'Kadıköy',
          level: TerritoryLevel.neighborhood,
          lat: 40.9906,
          lng: 29.0239,
          radiusMeters: 130,
          parentId: 'demo_istanbul',
        ),
        const Territory(
          id: 'demo_sultanahmet',
          name: 'Sultanahmet',
          level: TerritoryLevel.neighborhood,
          lat: 41.0055,
          lng: 28.9768,
          radiusMeters: 120,
          parentId: 'demo_istanbul',
        ),

        // ── Bangkok – neighborhoods ───────────────────────────────────────
        const Territory(
          id: 'demo_sukhumvit',
          name: 'Sukhumvit',
          level: TerritoryLevel.neighborhood,
          lat: 13.7307,
          lng: 100.5696,
          radiusMeters: 150,
          parentId: 'demo_bangkok',
        ),
        const Territory(
          id: 'demo_silom',
          name: 'Silom',
          level: TerritoryLevel.neighborhood,
          lat: 13.7235,
          lng: 100.5299,
          radiusMeters: 130,
          parentId: 'demo_bangkok',
        ),
        const Territory(
          id: 'demo_khao_san',
          name: 'Khao San Road',
          level: TerritoryLevel.neighborhood,
          lat: 13.7587,
          lng: 100.4970,
          radiusMeters: 100,
          parentId: 'demo_bangkok',
        ),

        // ── Mumbai – neighborhoods ────────────────────────────────────────
        const Territory(
          id: 'demo_bandra',
          name: 'Bandra',
          level: TerritoryLevel.neighborhood,
          lat: 19.0596,
          lng: 72.8295,
          radiusMeters: 140,
          parentId: 'demo_mumbai',
        ),
        const Territory(
          id: 'demo_colaba',
          name: 'Colaba',
          level: TerritoryLevel.neighborhood,
          lat: 18.9067,
          lng: 72.8147,
          radiusMeters: 120,
          parentId: 'demo_mumbai',
        ),
        const Territory(
          id: 'demo_juhu',
          name: 'Juhu',
          level: TerritoryLevel.neighborhood,
          lat: 19.1001,
          lng: 72.8268,
          radiusMeters: 130,
          parentId: 'demo_mumbai',
        ),

        // ── Beijing – neighborhoods ───────────────────────────────────────
        const Territory(
          id: 'demo_sanlitun',
          name: 'Sanlitun',
          level: TerritoryLevel.neighborhood,
          lat: 39.9330,
          lng: 116.4501,
          radiusMeters: 130,
          parentId: 'demo_beijing',
        ),
        const Territory(
          id: 'demo_wangfujing',
          name: 'Wangfujing',
          level: TerritoryLevel.neighborhood,
          lat: 39.9175,
          lng: 116.4097,
          radiusMeters: 120,
          parentId: 'demo_beijing',
        ),
        const Territory(
          id: 'demo_hutong',
          name: 'Hutong District',
          level: TerritoryLevel.neighborhood,
          lat: 39.9394,
          lng: 116.3961,
          radiusMeters: 130,
          parentId: 'demo_beijing',
        ),

        // ── Shanghai – neighborhoods ──────────────────────────────────────
        const Territory(
          id: 'demo_the_bund',
          name: 'The Bund',
          level: TerritoryLevel.neighborhood,
          lat: 31.2400,
          lng: 121.4908,
          radiusMeters: 130,
          parentId: 'demo_shanghai',
        ),
        const Territory(
          id: 'demo_french_concession',
          name: 'French Concession',
          level: TerritoryLevel.neighborhood,
          lat: 31.2209,
          lng: 121.4637,
          radiusMeters: 150,
          parentId: 'demo_shanghai',
        ),
        const Territory(
          id: 'demo_xintiandi',
          name: 'Xintiandi',
          level: TerritoryLevel.neighborhood,
          lat: 31.2200,
          lng: 121.4740,
          radiusMeters: 110,
          parentId: 'demo_shanghai',
        ),

        // ── Bangalore – neighborhoods ─────────────────────────────────────
        const Territory(
          id: 'demo_koramangala',
          name: 'Koramangala',
          level: TerritoryLevel.neighborhood,
          lat: 12.9352,
          lng: 77.6245,
          radiusMeters: 130,
          parentId: 'demo_bangalore',
        ),
        const Territory(
          id: 'demo_indiranagar',
          name: 'Indiranagar',
          level: TerritoryLevel.neighborhood,
          lat: 12.9784,
          lng: 77.6408,
          radiusMeters: 120,
          parentId: 'demo_bangalore',
        ),

        // ── Bogotá – neighborhoods ────────────────────────────────────────
        const Territory(
          id: 'demo_chapinero',
          name: 'Chapinero',
          level: TerritoryLevel.neighborhood,
          lat: 4.6480,
          lng: -74.0630,
          radiusMeters: 130,
          parentId: 'demo_bogota',
        ),
        const Territory(
          id: 'demo_la_candelaria',
          name: 'La Candelaria',
          level: TerritoryLevel.neighborhood,
          lat: 4.5981,
          lng: -74.0760,
          radiusMeters: 120,
          parentId: 'demo_bogota',
        ),

        // ── Cape Town – neighborhoods ─────────────────────────────────────
        const Territory(
          id: 'demo_v_a_waterfront',
          name: 'V&A Waterfront',
          level: TerritoryLevel.neighborhood,
          lat: -33.9050,
          lng: 18.4217,
          radiusMeters: 130,
          parentId: 'demo_cape_town',
        ),
        const Territory(
          id: 'demo_bo_kaap',
          name: 'Bo-Kaap',
          level: TerritoryLevel.neighborhood,
          lat: -33.9228,
          lng: 18.4155,
          radiusMeters: 110,
          parentId: 'demo_cape_town',
        ),

        // ── Johannesburg – neighborhoods ──────────────────────────────────
        const Territory(
          id: 'demo_sandton',
          name: 'Sandton',
          level: TerritoryLevel.neighborhood,
          lat: -26.1070,
          lng: 28.0567,
          radiusMeters: 150,
          parentId: 'demo_johannesburg',
        ),
        const Territory(
          id: 'demo_soweto',
          name: 'Soweto',
          level: TerritoryLevel.neighborhood,
          lat: -26.2677,
          lng: 27.8590,
          radiusMeters: 160,
          parentId: 'demo_johannesburg',
        ),

        // ── Vancouver – neighborhoods ─────────────────────────────────────
        const Territory(
          id: 'demo_gastown',
          name: 'Gastown',
          level: TerritoryLevel.neighborhood,
          lat: 49.2839,
          lng: -123.1083,
          radiusMeters: 110,
          parentId: 'demo_vancouver',
        ),
        const Territory(
          id: 'demo_kitsilano',
          name: 'Kitsilano',
          level: TerritoryLevel.neighborhood,
          lat: 49.2676,
          lng: -123.1681,
          radiusMeters: 140,
          parentId: 'demo_vancouver',
        ),
        const Territory(
          id: 'demo_granville_island',
          name: 'Granville Island',
          level: TerritoryLevel.neighborhood,
          lat: 49.2718,
          lng: -123.1341,
          radiusMeters: 110,
          parentId: 'demo_vancouver',
        ),

        // ── Montreal – neighborhoods ──────────────────────────────────────
        const Territory(
          id: 'demo_plateau_montreal',
          name: 'Le Plateau',
          level: TerritoryLevel.neighborhood,
          lat: 45.5225,
          lng: -73.5792,
          radiusMeters: 140,
          parentId: 'demo_montreal',
        ),
        const Territory(
          id: 'demo_old_montreal',
          name: 'Old Montreal',
          level: TerritoryLevel.neighborhood,
          lat: 45.5048,
          lng: -73.5565,
          radiusMeters: 130,
          parentId: 'demo_montreal',
        ),
        const Territory(
          id: 'demo_mile_end',
          name: 'Mile End',
          level: TerritoryLevel.neighborhood,
          lat: 45.5298,
          lng: -73.5982,
          radiusMeters: 120,
          parentId: 'demo_montreal',
        ),

        // ════════════════════════════════════════════════════════════════════
        // FULL TEXAS EXPANSION
        // ════════════════════════════════════════════════════════════════════

        // ── Texas Cities ──────────────────────────────────────────────────
        const Territory(
          id: 'demo_dallas',
          name: 'Dallas',
          level: TerritoryLevel.city,
          lat: 32.7767,
          lng: -96.7970,
          radiusMeters: 600,
          parentId: 'demo_texas',
        ),
        const Territory(
          id: 'demo_austin',
          name: 'Austin',
          level: TerritoryLevel.city,
          lat: 30.2672,
          lng: -97.7431,
          radiusMeters: 600,
          parentId: 'demo_texas',
        ),
        const Territory(
          id: 'demo_san_antonio',
          name: 'San Antonio',
          level: TerritoryLevel.city,
          lat: 29.4241,
          lng: -98.4936,
          radiusMeters: 25000,
          parentId: 'demo_texas',
        ),
        const Territory(
          id: 'demo_fort_worth',
          name: 'Fort Worth',
          level: TerritoryLevel.city,
          lat: 32.7555,
          lng: -97.3308,
          radiusMeters: 600,
          parentId: 'demo_texas',
        ),
        const Territory(
          id: 'demo_el_paso',
          name: 'El Paso',
          level: TerritoryLevel.city,
          lat: 31.7619,
          lng: -106.4850,
          radiusMeters: 600,
          parentId: 'demo_texas',
        ),
        const Territory(
          id: 'demo_arlington',
          name: 'Arlington',
          level: TerritoryLevel.city,
          lat: 32.7357,
          lng: -97.1081,
          radiusMeters: 500,
          parentId: 'demo_texas',
        ),
        const Territory(
          id: 'demo_plano',
          name: 'Plano',
          level: TerritoryLevel.city,
          lat: 33.0198,
          lng: -96.6989,
          radiusMeters: 500,
          parentId: 'demo_texas',
        ),
        const Territory(
          id: 'demo_corpus_christi',
          name: 'Corpus Christi',
          level: TerritoryLevel.city,
          lat: 27.8006,
          lng: -97.3964,
          radiusMeters: 500,
          parentId: 'demo_texas',
        ),
        const Territory(
          id: 'demo_lubbock',
          name: 'Lubbock',
          level: TerritoryLevel.city,
          lat: 33.5779,
          lng: -101.8552,
          radiusMeters: 500,
          parentId: 'demo_texas',
        ),
        const Territory(
          id: 'demo_amarillo',
          name: 'Amarillo',
          level: TerritoryLevel.city,
          lat: 35.2220,
          lng: -101.8313,
          radiusMeters: 500,
          parentId: 'demo_texas',
        ),
        const Territory(
          id: 'demo_galveston',
          name: 'Galveston',
          level: TerritoryLevel.city,
          lat: 29.3013,
          lng: -94.7977,
          radiusMeters: 400,
          parentId: 'demo_texas',
        ),
        const Territory(
          id: 'demo_irving',
          name: 'Irving',
          level: TerritoryLevel.city,
          lat: 32.8140,
          lng: -96.9489,
          radiusMeters: 450,
          parentId: 'demo_texas',
        ),
        const Territory(
          id: 'demo_waco',
          name: 'Waco',
          level: TerritoryLevel.city,
          lat: 31.5493,
          lng: -97.1467,
          radiusMeters: 450,
          parentId: 'demo_texas',
        ),
        const Territory(
          id: 'demo_laredo',
          name: 'Laredo',
          level: TerritoryLevel.city,
          lat: 27.5306,
          lng: -99.4803,
          radiusMeters: 450,
          parentId: 'demo_texas',
        ),
        const Territory(
          id: 'demo_mcallen',
          name: 'McAllen',
          level: TerritoryLevel.city,
          lat: 26.2034,
          lng: -98.2300,
          radiusMeters: 450,
          parentId: 'demo_texas',
        ),

        // ── Houston neighborhoods ─────────────────────────────────────────
        const Territory(
          id: 'demo_downtown_houston',
          name: 'Downtown Houston',
          level: TerritoryLevel.neighborhood,
          lat: 29.7604,
          lng: -95.3698,
          radiusMeters: 130,
          parentId: 'demo_houston',
        ),
        const Territory(
          id: 'demo_montrose_hou',
          name: 'Montrose',
          level: TerritoryLevel.neighborhood,
          lat: 29.7417,
          lng: -95.3900,
          radiusMeters: 130,
          parentId: 'demo_houston',
        ),
        const Territory(
          id: 'demo_the_heights_hou',
          name: 'The Heights',
          level: TerritoryLevel.neighborhood,
          lat: 29.7946,
          lng: -95.3941,
          radiusMeters: 140,
          parentId: 'demo_houston',
        ),
        const Territory(
          id: 'demo_midtown_hou',
          name: 'Midtown Houston',
          level: TerritoryLevel.neighborhood,
          lat: 29.7420,
          lng: -95.3722,
          radiusMeters: 120,
          parentId: 'demo_houston',
        ),
        const Territory(
          id: 'demo_museum_district_hou',
          name: 'Museum District',
          level: TerritoryLevel.neighborhood,
          lat: 29.7217,
          lng: -95.3875,
          radiusMeters: 130,
          parentId: 'demo_houston',
        ),
        const Territory(
          id: 'demo_river_oaks_hou',
          name: 'River Oaks',
          level: TerritoryLevel.neighborhood,
          lat: 29.7521,
          lng: -95.4267,
          radiusMeters: 140,
          parentId: 'demo_houston',
        ),
        const Territory(
          id: 'demo_eado_hou',
          name: 'EaDo',
          level: TerritoryLevel.neighborhood,
          lat: 29.7543,
          lng: -95.3456,
          radiusMeters: 120,
          parentId: 'demo_houston',
        ),
        const Territory(
          id: 'demo_upper_kirby_hou',
          name: 'Upper Kirby',
          level: TerritoryLevel.neighborhood,
          lat: 29.7305,
          lng: -95.4282,
          radiusMeters: 120,
          parentId: 'demo_houston',
        ),
        const Territory(
          id: 'demo_energy_corridor_hou',
          name: 'Energy Corridor',
          level: TerritoryLevel.neighborhood,
          lat: 29.7665,
          lng: -95.5972,
          radiusMeters: 150,
          parentId: 'demo_houston',
        ),

        // ── Dallas neighborhoods ──────────────────────────────────────────
        const Territory(
          id: 'demo_deep_ellum',
          name: 'Deep Ellum',
          level: TerritoryLevel.neighborhood,
          lat: 32.7862,
          lng: -96.7837,
          radiusMeters: 120,
          parentId: 'demo_dallas',
        ),
        const Territory(
          id: 'demo_uptown_dallas',
          name: 'Uptown',
          level: TerritoryLevel.neighborhood,
          lat: 32.7998,
          lng: -96.8011,
          radiusMeters: 130,
          parentId: 'demo_dallas',
        ),
        const Territory(
          id: 'demo_bishop_arts',
          name: 'Bishop Arts District',
          level: TerritoryLevel.neighborhood,
          lat: 32.7475,
          lng: -96.8330,
          radiusMeters: 110,
          parentId: 'demo_dallas',
        ),
        const Territory(
          id: 'demo_design_district_dal',
          name: 'Design District',
          level: TerritoryLevel.neighborhood,
          lat: 32.7956,
          lng: -96.8293,
          radiusMeters: 120,
          parentId: 'demo_dallas',
        ),
        const Territory(
          id: 'demo_oak_cliff',
          name: 'Oak Cliff',
          level: TerritoryLevel.neighborhood,
          lat: 32.7432,
          lng: -96.8398,
          radiusMeters: 140,
          parentId: 'demo_dallas',
        ),
        const Territory(
          id: 'demo_knox_henderson',
          name: 'Knox-Henderson',
          level: TerritoryLevel.neighborhood,
          lat: 32.8173,
          lng: -96.7927,
          radiusMeters: 110,
          parentId: 'demo_dallas',
        ),
        const Territory(
          id: 'demo_lower_greenville',
          name: 'Lower Greenville',
          level: TerritoryLevel.neighborhood,
          lat: 32.8182,
          lng: -96.7803,
          radiusMeters: 110,
          parentId: 'demo_dallas',
        ),
        const Territory(
          id: 'demo_downtown_dallas',
          name: 'Downtown Dallas',
          level: TerritoryLevel.neighborhood,
          lat: 32.7767,
          lng: -96.7970,
          radiusMeters: 130,
          parentId: 'demo_dallas',
        ),

        // ── Austin neighborhoods ──────────────────────────────────────────
        const Territory(
          id: 'demo_sixth_street_aus',
          name: '6th Street',
          level: TerritoryLevel.neighborhood,
          lat: 30.2689,
          lng: -97.7405,
          radiusMeters: 100,
          parentId: 'demo_austin',
        ),
        const Territory(
          id: 'demo_south_congress_aus',
          name: 'South Congress',
          level: TerritoryLevel.neighborhood,
          lat: 30.2480,
          lng: -97.7504,
          radiusMeters: 130,
          parentId: 'demo_austin',
        ),
        const Territory(
          id: 'demo_east_austin',
          name: 'East Austin',
          level: TerritoryLevel.neighborhood,
          lat: 30.2688,
          lng: -97.7218,
          radiusMeters: 140,
          parentId: 'demo_austin',
        ),
        const Territory(
          id: 'demo_zilker_aus',
          name: 'Zilker',
          level: TerritoryLevel.neighborhood,
          lat: 30.2665,
          lng: -97.7709,
          radiusMeters: 130,
          parentId: 'demo_austin',
        ),
        const Territory(
          id: 'demo_the_domain_aus',
          name: 'The Domain',
          level: TerritoryLevel.neighborhood,
          lat: 30.4025,
          lng: -97.7243,
          radiusMeters: 140,
          parentId: 'demo_austin',
        ),
        const Territory(
          id: 'demo_rainey_street_aus',
          name: 'Rainey Street',
          level: TerritoryLevel.neighborhood,
          lat: 30.2596,
          lng: -97.7378,
          radiusMeters: 100,
          parentId: 'demo_austin',
        ),
        const Territory(
          id: 'demo_mueller_aus',
          name: 'Mueller',
          level: TerritoryLevel.neighborhood,
          lat: 30.2982,
          lng: -97.6972,
          radiusMeters: 130,
          parentId: 'demo_austin',
        ),
        const Territory(
          id: 'demo_south_lamar_aus',
          name: 'South Lamar',
          level: TerritoryLevel.neighborhood,
          lat: 30.2499,
          lng: -97.7686,
          radiusMeters: 120,
          parentId: 'demo_austin',
        ),

        // ── San Antonio neighborhoods ─────────────────────────────────────
        const Territory(
          id: 'demo_river_walk_sa',
          name: 'River Walk',
          level: TerritoryLevel.neighborhood,
          lat: 29.4241,
          lng: -98.4936,
          radiusMeters: 800,
          parentId: 'demo_san_antonio',
        ),
        const Territory(
          id: 'demo_alamo_heights_sa',
          name: 'Alamo Heights',
          level: TerritoryLevel.neighborhood,
          lat: 29.4719,
          lng: -98.4712,
          radiusMeters: 1000,
          parentId: 'demo_san_antonio',
        ),
        const Territory(
          id: 'demo_pearl_district_sa',
          name: 'Pearl District',
          level: TerritoryLevel.neighborhood,
          lat: 29.4440,
          lng: -98.4853,
          radiusMeters: 700,
          parentId: 'demo_san_antonio',
        ),
        const Territory(
          id: 'demo_king_william_sa',
          name: 'King William',
          level: TerritoryLevel.neighborhood,
          lat: 29.4147,
          lng: -98.4892,
          radiusMeters: 600,
          parentId: 'demo_san_antonio',
        ),
        const Territory(
          id: 'demo_southtown_sa',
          name: 'Southtown',
          level: TerritoryLevel.neighborhood,
          lat: 29.4093,
          lng: -98.4892,
          radiusMeters: 700,
          parentId: 'demo_san_antonio',
        ),
        const Territory(
          id: 'demo_monte_vista_sa',
          name: 'Monte Vista',
          level: TerritoryLevel.neighborhood,
          lat: 29.4581,
          lng: -98.5041,
          radiusMeters: 900,
          parentId: 'demo_san_antonio',
        ),
        const Territory(
          id: 'demo_stone_oak_sa',
          name: 'Stone Oak',
          level: TerritoryLevel.neighborhood,
          lat: 29.5941,
          lng: -98.4914,
          radiusMeters: 1200,
          parentId: 'demo_san_antonio',
        ),

        // ── Fort Worth neighborhoods ──────────────────────────────────────
        const Territory(
          id: 'demo_stockyards_fw',
          name: 'Fort Worth Stockyards',
          level: TerritoryLevel.neighborhood,
          lat: 32.7900,
          lng: -97.3486,
          radiusMeters: 130,
          parentId: 'demo_fort_worth',
        ),
        const Territory(
          id: 'demo_sundance_square_fw',
          name: 'Sundance Square',
          level: TerritoryLevel.neighborhood,
          lat: 32.7517,
          lng: -97.3308,
          radiusMeters: 110,
          parentId: 'demo_fort_worth',
        ),
        const Territory(
          id: 'demo_cultural_district_fw',
          name: 'Cultural District',
          level: TerritoryLevel.neighborhood,
          lat: 32.7483,
          lng: -97.3756,
          radiusMeters: 130,
          parentId: 'demo_fort_worth',
        ),
        const Territory(
          id: 'demo_camp_bowie_fw',
          name: 'Camp Bowie',
          level: TerritoryLevel.neighborhood,
          lat: 32.7431,
          lng: -97.3960,
          radiusMeters: 140,
          parentId: 'demo_fort_worth',
        ),
        const Territory(
          id: 'demo_near_southside_fw',
          name: 'Near Southside',
          level: TerritoryLevel.neighborhood,
          lat: 32.7315,
          lng: -97.3272,
          radiusMeters: 120,
          parentId: 'demo_fort_worth',
        ),

        // ── El Paso neighborhoods ─────────────────────────────────────────
        const Territory(
          id: 'demo_downtown_ep',
          name: 'Downtown El Paso',
          level: TerritoryLevel.neighborhood,
          lat: 31.7619,
          lng: -106.4850,
          radiusMeters: 120,
          parentId: 'demo_el_paso',
        ),
        const Territory(
          id: 'demo_kern_place_ep',
          name: 'Kern Place',
          level: TerritoryLevel.neighborhood,
          lat: 31.8016,
          lng: -106.4833,
          radiusMeters: 110,
          parentId: 'demo_el_paso',
        ),
        const Territory(
          id: 'demo_sunset_heights_ep',
          name: 'Sunset Heights',
          level: TerritoryLevel.neighborhood,
          lat: 31.7744,
          lng: -106.4952,
          radiusMeters: 120,
          parentId: 'demo_el_paso',
        ),
        const Territory(
          id: 'demo_mission_hills_ep',
          name: 'Mission Hills',
          level: TerritoryLevel.neighborhood,
          lat: 31.7985,
          lng: -106.5138,
          radiusMeters: 130,
          parentId: 'demo_el_paso',
        ),

        // ── Galveston neighborhoods ───────────────────────────────────────
        const Territory(
          id: 'demo_strand_galv',
          name: 'The Strand',
          level: TerritoryLevel.neighborhood,
          lat: 29.3095,
          lng: -94.7949,
          radiusMeters: 110,
          parentId: 'demo_galveston',
        ),
        const Territory(
          id: 'demo_east_beach_galv',
          name: 'East Beach',
          level: TerritoryLevel.neighborhood,
          lat: 29.3010,
          lng: -94.7386,
          radiusMeters: 120,
          parentId: 'demo_galveston',
        ),
        const Territory(
          id: 'demo_seawall_galv',
          name: 'Seawall Boulevard',
          level: TerritoryLevel.neighborhood,
          lat: 29.2813,
          lng: -94.8306,
          radiusMeters: 130,
          parentId: 'demo_galveston',
        ),

        // ── Waco neighborhoods ────────────────────────────────────────────
        const Territory(
          id: 'demo_magnolia_waco',
          name: 'Magnolia Market',
          level: TerritoryLevel.neighborhood,
          lat: 31.5436,
          lng: -97.1489,
          radiusMeters: 110,
          parentId: 'demo_waco',
        ),
        const Territory(
          id: 'demo_baylor_waco',
          name: 'Baylor University Area',
          level: TerritoryLevel.neighborhood,
          lat: 31.5488,
          lng: -97.1131,
          radiusMeters: 130,
          parentId: 'demo_waco',
        ),
        const Territory(
          id: 'demo_downtown_waco',
          name: 'Downtown Waco',
          level: TerritoryLevel.neighborhood,
          lat: 31.5493,
          lng: -97.1467,
          radiusMeters: 120,
          parentId: 'demo_waco',
        ),

        // ════════════════════════════════════════════════════════════════════
        // YOUR LOCATION — 3400 NORTHEAST PKWY, SAN ANTONIO TX
        // Full 20-mile radius coverage
        // ════════════════════════════════════════════════════════════════════

        // ── Exact location ────────────────────────────────────────────────
        const Territory(
          id: 'demo_your_location',
          name: '3400 NE Pkwy',
          level: TerritoryLevel.neighborhood,
          lat: 29.5155,
          lng: -98.4558,
          radiusMeters: 150,
          parentId: 'demo_san_antonio',
        ),

        // ── Immediate neighborhoods within ~5 miles ───────────────────────
        const Territory(
          id: 'demo_oak_park_sa',
          name: 'Oak Park',
          level: TerritoryLevel.neighborhood,
          lat: 29.5340,
          lng: -98.4630,
          radiusMeters: 900,
          parentId: 'demo_san_antonio',
        ),
        const Territory(
          id: 'demo_thousand_oaks_sa',
          name: 'Thousand Oaks',
          level: TerritoryLevel.neighborhood,
          lat: 29.5310,
          lng: -98.4390,
          radiusMeters: 900,
          parentId: 'demo_san_antonio',
        ),
        const Territory(
          id: 'demo_northwood_hills_sa',
          name: 'Northwood Hills',
          level: TerritoryLevel.neighborhood,
          lat: 29.5250,
          lng: -98.4760,
          radiusMeters: 900,
          parentId: 'demo_san_antonio',
        ),
        const Territory(
          id: 'demo_terrell_hills_sa',
          name: 'Terrell Hills',
          level: TerritoryLevel.neighborhood,
          lat: 29.4748,
          lng: -98.4513,
          radiusMeters: 800,
          parentId: 'demo_san_antonio',
        ),
        const Territory(
          id: 'demo_fort_sam_houston_sa',
          name: 'Fort Sam Houston',
          level: TerritoryLevel.neighborhood,
          lat: 29.4635,
          lng: -98.4298,
          radiusMeters: 1200,
          parentId: 'demo_san_antonio',
        ),
        const Territory(
          id: 'demo_windcrest_sa',
          name: 'Windcrest',
          level: TerritoryLevel.neighborhood,
          lat: 29.5161,
          lng: -98.4152,
          radiusMeters: 900,
          parentId: 'demo_san_antonio',
        ),
        const Territory(
          id: 'demo_north_star_sa',
          name: 'North Star',
          level: TerritoryLevel.neighborhood,
          lat: 29.5300,
          lng: -98.4920,
          radiusMeters: 900,
          parentId: 'demo_san_antonio',
        ),
        const Territory(
          id: 'demo_harry_wurzbach_sa',
          name: 'Harry Wurzbach',
          level: TerritoryLevel.neighborhood,
          lat: 29.5022,
          lng: -98.4621,
          radiusMeters: 800,
          parentId: 'demo_san_antonio',
        ),
        const Territory(
          id: 'demo_sunset_ridge_sa',
          name: 'Sunset Ridge',
          level: TerritoryLevel.neighborhood,
          lat: 29.5480,
          lng: -98.4510,
          radiusMeters: 900,
          parentId: 'demo_san_antonio',
        ),
        const Territory(
          id: 'demo_tobin_hill_sa',
          name: 'Tobin Hill',
          level: TerritoryLevel.neighborhood,
          lat: 29.4510,
          lng: -98.4798,
          radiusMeters: 700,
          parentId: 'demo_san_antonio',
        ),
        const Territory(
          id: 'demo_midtown_sa',
          name: 'Midtown San Antonio',
          level: TerritoryLevel.neighborhood,
          lat: 29.4390,
          lng: -98.4960,
          radiusMeters: 900,
          parentId: 'demo_san_antonio',
        ),

        // ── Surrounding cities 5–20 miles out ────────────────────────────
        const Territory(
          id: 'demo_live_oak_tx',
          name: 'Live Oak',
          level: TerritoryLevel.city,
          lat: 29.5649,
          lng: -98.3449,
          radiusMeters: 2500,
          parentId: 'demo_texas',
        ),
        const Territory(
          id: 'demo_universal_city_tx',
          name: 'Universal City',
          level: TerritoryLevel.city,
          lat: 29.5413,
          lng: -98.2921,
          radiusMeters: 2000,
          parentId: 'demo_texas',
        ),
        const Territory(
          id: 'demo_converse_tx',
          name: 'Converse',
          level: TerritoryLevel.city,
          lat: 29.5086,
          lng: -98.3208,
          radiusMeters: 2500,
          parentId: 'demo_texas',
        ),
        const Territory(
          id: 'demo_selma_tx',
          name: 'Selma',
          level: TerritoryLevel.city,
          lat: 29.5780,
          lng: -98.3141,
          radiusMeters: 1500,
          parentId: 'demo_texas',
        ),
        const Territory(
          id: 'demo_schertz_tx',
          name: 'Schertz',
          level: TerritoryLevel.city,
          lat: 29.5563,
          lng: -98.2693,
          radiusMeters: 3000,
          parentId: 'demo_texas',
        ),
        const Territory(
          id: 'demo_cibolo_tx',
          name: 'Cibolo',
          level: TerritoryLevel.city,
          lat: 29.5588,
          lng: -98.2280,
          radiusMeters: 2500,
          parentId: 'demo_texas',
        ),
        const Territory(
          id: 'demo_shavano_park_tx',
          name: 'Shavano Park',
          level: TerritoryLevel.city,
          lat: 29.5743,
          lng: -98.5038,
          radiusMeters: 1500,
          parentId: 'demo_texas',
        ),
        const Territory(
          id: 'demo_hollywood_park_tx',
          name: 'Hollywood Park',
          level: TerritoryLevel.city,
          lat: 29.5713,
          lng: -98.4769,
          radiusMeters: 1200,
          parentId: 'demo_texas',
        ),
        const Territory(
          id: 'demo_castle_hills_tx',
          name: 'Castle Hills',
          level: TerritoryLevel.city,
          lat: 29.5239,
          lng: -98.5167,
          radiusMeters: 1500,
          parentId: 'demo_texas',
        ),
        const Territory(
          id: 'demo_leon_valley_tx',
          name: 'Leon Valley',
          level: TerritoryLevel.city,
          lat: 29.4960,
          lng: -98.6059,
          radiusMeters: 2500,
          parentId: 'demo_texas',
        ),
        const Territory(
          id: 'demo_helotes_tx',
          name: 'Helotes',
          level: TerritoryLevel.city,
          lat: 29.5757,
          lng: -98.6873,
          radiusMeters: 3000,
          parentId: 'demo_texas',
        ),
        const Territory(
          id: 'demo_fair_oaks_ranch_tx',
          name: 'Fair Oaks Ranch',
          level: TerritoryLevel.city,
          lat: 29.7399,
          lng: -98.6368,
          radiusMeters: 2500,
          parentId: 'demo_texas',
        ),
        const Territory(
          id: 'demo_boerne_tx',
          name: 'Boerne',
          level: TerritoryLevel.city,
          lat: 29.7947,
          lng: -98.7320,
          radiusMeters: 3000,
          parentId: 'demo_texas',
        ),
        const Territory(
          id: 'demo_new_braunfels_tx',
          name: 'New Braunfels',
          level: TerritoryLevel.city,
          lat: 29.7030,
          lng: -98.1245,
          radiusMeters: 4000,
          parentId: 'demo_texas',
        ),
        const Territory(
          id: 'demo_seguin_tx',
          name: 'Seguin',
          level: TerritoryLevel.city,
          lat: 29.5688,
          lng: -97.9644,
          radiusMeters: 3000,
          parentId: 'demo_texas',
        ),
        const Territory(
          id: 'demo_kirby_tx',
          name: 'Kirby',
          level: TerritoryLevel.city,
          lat: 29.4593,
          lng: -98.3900,
          radiusMeters: 1200,
          parentId: 'demo_texas',
        ),
        const Territory(
          id: 'demo_elmendorf_tx',
          name: 'Elmendorf',
          level: TerritoryLevel.city,
          lat: 29.2538,
          lng: -98.3178,
          radiusMeters: 1500,
          parentId: 'demo_texas',
        ),
        const Territory(
          id: 'demo_von_ormy_tx',
          name: 'Von Ormy',
          level: TerritoryLevel.city,
          lat: 29.3049,
          lng: -98.6489,
          radiusMeters: 1200,
          parentId: 'demo_texas',
        ),

        // ── Neighborhoods in nearby suburb cities ─────────────────────────
        const Territory(
          id: 'demo_randolph_afb_ucity',
          name: 'Randolph AFB Area',
          level: TerritoryLevel.neighborhood,
          lat: 29.5299,
          lng: -98.2799,
          radiusMeters: 700,
          parentId: 'demo_universal_city_tx',
        ),
        const Territory(
          id: 'demo_downtown_schertz',
          name: 'Downtown Schertz',
          level: TerritoryLevel.neighborhood,
          lat: 29.5563,
          lng: -98.2693,
          radiusMeters: 500,
          parentId: 'demo_schertz_tx',
        ),
        const Territory(
          id: 'demo_downtown_new_braunfels',
          name: 'Downtown New Braunfels',
          level: TerritoryLevel.neighborhood,
          lat: 29.7030,
          lng: -98.1245,
          radiusMeters: 600,
          parentId: 'demo_new_braunfels_tx',
        ),
        const Territory(
          id: 'demo_comal_springs_nb',
          name: 'Comal Springs',
          level: TerritoryLevel.neighborhood,
          lat: 29.7115,
          lng: -98.1271,
          radiusMeters: 500,
          parentId: 'demo_new_braunfels_tx',
        ),
        const Territory(
          id: 'demo_gruene_nb',
          name: 'Gruene',
          level: TerritoryLevel.neighborhood,
          lat: 29.7391,
          lng: -98.1036,
          radiusMeters: 500,
          parentId: 'demo_new_braunfels_tx',
        ),
        const Territory(
          id: 'demo_main_plaza_boerne',
          name: 'Main Plaza Boerne',
          level: TerritoryLevel.neighborhood,
          lat: 29.7947,
          lng: -98.7320,
          radiusMeters: 500,
          parentId: 'demo_boerne_tx',
        ),
        const Territory(
          id: 'demo_ciclo_helotes',
          name: 'Old Helotes',
          level: TerritoryLevel.neighborhood,
          lat: 29.5757,
          lng: -98.6873,
          radiusMeters: 600,
          parentId: 'demo_helotes_tx',
        ),
      ];
}
